spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/store?&useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB    # 单个文件上传大小限制
      max-request-size: 100MB  #一次请求上传文件大小总限制


#&serverTimezone=CTT

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pirvate.store.entity

address:
  max-count: 20