package com.pirvate.store.mapper;

import com.pirvate.store.entity.DictDistrict;
import com.pirvate.store.entity.DictDistrictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictDistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int countByExample(DictDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int deleteByExample(DictDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int insert(DictDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int insertSelective(DictDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    List<DictDistrict> selectByExample(DictDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    DictDistrict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int updateByExampleSelective(@Param("record") DictDistrict record, @Param("example") DictDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int updateByExample(@Param("record") DictDistrict record, @Param("example") DictDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int updateByPrimaryKeySelective(DictDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_district
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int updateByPrimaryKey(DictDistrict record);
}