package com.pirvate.store.mapper;

import com.pirvate.store.entity.ProductCategory;
import com.pirvate.store.entity.ProductCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_category
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int countByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_category
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int deleteByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_category
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_category
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int insert(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_category
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int insertSelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_category
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    List<ProductCategory> selectByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_category
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    ProductCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_category
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int updateByExampleSelective(@Param("record") ProductCategory record, @Param("example") ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_category
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int updateByExample(@Param("record") ProductCategory record, @Param("example") ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_category
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int updateByPrimaryKeySelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_category
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    int updateByPrimaryKey(ProductCategory record);
}