package com.pirvate.store.entity;

import lombok.ToString;

import java.util.Date;

@ToString
public class Cart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.cid
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.uid
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.pid
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.price
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.num
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.created_user
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private String createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.created_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.modified_user
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private String modifiedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cart.modified_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Date modifiedTime;

    private Product product;

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.cid
     *
     * @return the value of t_cart.cid
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.cid
     *
     * @param cid the value for t_cart.cid
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.uid
     *
     * @return the value of t_cart.uid
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.uid
     *
     * @param uid the value for t_cart.uid
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.pid
     *
     * @return the value of t_cart.pid
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.pid
     *
     * @param pid the value for t_cart.pid
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.price
     *
     * @return the value of t_cart.price
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.price
     *
     * @param price the value for t_cart.price
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.num
     *
     * @return the value of t_cart.num
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.num
     *
     * @param num the value for t_cart.num
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.created_user
     *
     * @return the value of t_cart.created_user
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.created_user
     *
     * @param createdUser the value for t_cart.created_user
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser == null ? null : createdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.created_time
     *
     * @return the value of t_cart.created_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.created_time
     *
     * @param createdTime the value for t_cart.created_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.modified_user
     *
     * @return the value of t_cart.modified_user
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public String getModifiedUser() {
        return modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.modified_user
     *
     * @param modifiedUser the value for t_cart.modified_user
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setModifiedUser(String modifiedUser) {
        this.modifiedUser = modifiedUser == null ? null : modifiedUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cart.modified_time
     *
     * @return the value of t_cart.modified_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cart.modified_time
     *
     * @param modifiedTime the value for t_cart.modified_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}