package com.pirvate.store.entity;

import lombok.ToString;

@ToString
public class DictDistrict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_district.id
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_district.parent
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private String parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_district.code
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_district.name
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_district.id
     *
     * @return the value of t_dict_district.id
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_district.id
     *
     * @param id the value for t_dict_district.id
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_district.parent
     *
     * @return the value of t_dict_district.parent
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_district.parent
     *
     * @param parent the value for t_dict_district.parent
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setParent(String parent) {
        this.parent = parent == null ? null : parent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_district.code
     *
     * @return the value of t_dict_district.code
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_district.code
     *
     * @param code the value for t_dict_district.code
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_district.name
     *
     * @return the value of t_dict_district.name
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_district.name
     *
     * @param name the value for t_dict_district.name
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}