package com.pirvate.store.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOidIsNull() {
            addCriterion("oid is null");
            return (Criteria) this;
        }

        public Criteria andOidIsNotNull() {
            addCriterion("oid is not null");
            return (Criteria) this;
        }

        public Criteria andOidEqualTo(Integer value) {
            addCriterion("oid =", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotEqualTo(Integer value) {
            addCriterion("oid <>", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThan(Integer value) {
            addCriterion("oid >", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThanOrEqualTo(Integer value) {
            addCriterion("oid >=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThan(Integer value) {
            addCriterion("oid <", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThanOrEqualTo(Integer value) {
            addCriterion("oid <=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidIn(List<Integer> values) {
            addCriterion("oid in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotIn(List<Integer> values) {
            addCriterion("oid not in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidBetween(Integer value1, Integer value2) {
            addCriterion("oid between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotBetween(Integer value1, Integer value2) {
            addCriterion("oid not between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andRecvNameIsNull() {
            addCriterion("recv_name is null");
            return (Criteria) this;
        }

        public Criteria andRecvNameIsNotNull() {
            addCriterion("recv_name is not null");
            return (Criteria) this;
        }

        public Criteria andRecvNameEqualTo(String value) {
            addCriterion("recv_name =", value, "recvName");
            return (Criteria) this;
        }

        public Criteria andRecvNameNotEqualTo(String value) {
            addCriterion("recv_name <>", value, "recvName");
            return (Criteria) this;
        }

        public Criteria andRecvNameGreaterThan(String value) {
            addCriterion("recv_name >", value, "recvName");
            return (Criteria) this;
        }

        public Criteria andRecvNameGreaterThanOrEqualTo(String value) {
            addCriterion("recv_name >=", value, "recvName");
            return (Criteria) this;
        }

        public Criteria andRecvNameLessThan(String value) {
            addCriterion("recv_name <", value, "recvName");
            return (Criteria) this;
        }

        public Criteria andRecvNameLessThanOrEqualTo(String value) {
            addCriterion("recv_name <=", value, "recvName");
            return (Criteria) this;
        }

        public Criteria andRecvNameLike(String value) {
            addCriterion("recv_name like", value, "recvName");
            return (Criteria) this;
        }

        public Criteria andRecvNameNotLike(String value) {
            addCriterion("recv_name not like", value, "recvName");
            return (Criteria) this;
        }

        public Criteria andRecvNameIn(List<String> values) {
            addCriterion("recv_name in", values, "recvName");
            return (Criteria) this;
        }

        public Criteria andRecvNameNotIn(List<String> values) {
            addCriterion("recv_name not in", values, "recvName");
            return (Criteria) this;
        }

        public Criteria andRecvNameBetween(String value1, String value2) {
            addCriterion("recv_name between", value1, value2, "recvName");
            return (Criteria) this;
        }

        public Criteria andRecvNameNotBetween(String value1, String value2) {
            addCriterion("recv_name not between", value1, value2, "recvName");
            return (Criteria) this;
        }

        public Criteria andRecvPhoneIsNull() {
            addCriterion("recv_phone is null");
            return (Criteria) this;
        }

        public Criteria andRecvPhoneIsNotNull() {
            addCriterion("recv_phone is not null");
            return (Criteria) this;
        }

        public Criteria andRecvPhoneEqualTo(String value) {
            addCriterion("recv_phone =", value, "recvPhone");
            return (Criteria) this;
        }

        public Criteria andRecvPhoneNotEqualTo(String value) {
            addCriterion("recv_phone <>", value, "recvPhone");
            return (Criteria) this;
        }

        public Criteria andRecvPhoneGreaterThan(String value) {
            addCriterion("recv_phone >", value, "recvPhone");
            return (Criteria) this;
        }

        public Criteria andRecvPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("recv_phone >=", value, "recvPhone");
            return (Criteria) this;
        }

        public Criteria andRecvPhoneLessThan(String value) {
            addCriterion("recv_phone <", value, "recvPhone");
            return (Criteria) this;
        }

        public Criteria andRecvPhoneLessThanOrEqualTo(String value) {
            addCriterion("recv_phone <=", value, "recvPhone");
            return (Criteria) this;
        }

        public Criteria andRecvPhoneLike(String value) {
            addCriterion("recv_phone like", value, "recvPhone");
            return (Criteria) this;
        }

        public Criteria andRecvPhoneNotLike(String value) {
            addCriterion("recv_phone not like", value, "recvPhone");
            return (Criteria) this;
        }

        public Criteria andRecvPhoneIn(List<String> values) {
            addCriterion("recv_phone in", values, "recvPhone");
            return (Criteria) this;
        }

        public Criteria andRecvPhoneNotIn(List<String> values) {
            addCriterion("recv_phone not in", values, "recvPhone");
            return (Criteria) this;
        }

        public Criteria andRecvPhoneBetween(String value1, String value2) {
            addCriterion("recv_phone between", value1, value2, "recvPhone");
            return (Criteria) this;
        }

        public Criteria andRecvPhoneNotBetween(String value1, String value2) {
            addCriterion("recv_phone not between", value1, value2, "recvPhone");
            return (Criteria) this;
        }

        public Criteria andRecvProvinceIsNull() {
            addCriterion("recv_province is null");
            return (Criteria) this;
        }

        public Criteria andRecvProvinceIsNotNull() {
            addCriterion("recv_province is not null");
            return (Criteria) this;
        }

        public Criteria andRecvProvinceEqualTo(String value) {
            addCriterion("recv_province =", value, "recvProvince");
            return (Criteria) this;
        }

        public Criteria andRecvProvinceNotEqualTo(String value) {
            addCriterion("recv_province <>", value, "recvProvince");
            return (Criteria) this;
        }

        public Criteria andRecvProvinceGreaterThan(String value) {
            addCriterion("recv_province >", value, "recvProvince");
            return (Criteria) this;
        }

        public Criteria andRecvProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("recv_province >=", value, "recvProvince");
            return (Criteria) this;
        }

        public Criteria andRecvProvinceLessThan(String value) {
            addCriterion("recv_province <", value, "recvProvince");
            return (Criteria) this;
        }

        public Criteria andRecvProvinceLessThanOrEqualTo(String value) {
            addCriterion("recv_province <=", value, "recvProvince");
            return (Criteria) this;
        }

        public Criteria andRecvProvinceLike(String value) {
            addCriterion("recv_province like", value, "recvProvince");
            return (Criteria) this;
        }

        public Criteria andRecvProvinceNotLike(String value) {
            addCriterion("recv_province not like", value, "recvProvince");
            return (Criteria) this;
        }

        public Criteria andRecvProvinceIn(List<String> values) {
            addCriterion("recv_province in", values, "recvProvince");
            return (Criteria) this;
        }

        public Criteria andRecvProvinceNotIn(List<String> values) {
            addCriterion("recv_province not in", values, "recvProvince");
            return (Criteria) this;
        }

        public Criteria andRecvProvinceBetween(String value1, String value2) {
            addCriterion("recv_province between", value1, value2, "recvProvince");
            return (Criteria) this;
        }

        public Criteria andRecvProvinceNotBetween(String value1, String value2) {
            addCriterion("recv_province not between", value1, value2, "recvProvince");
            return (Criteria) this;
        }

        public Criteria andRecvCityIsNull() {
            addCriterion("recv_city is null");
            return (Criteria) this;
        }

        public Criteria andRecvCityIsNotNull() {
            addCriterion("recv_city is not null");
            return (Criteria) this;
        }

        public Criteria andRecvCityEqualTo(String value) {
            addCriterion("recv_city =", value, "recvCity");
            return (Criteria) this;
        }

        public Criteria andRecvCityNotEqualTo(String value) {
            addCriterion("recv_city <>", value, "recvCity");
            return (Criteria) this;
        }

        public Criteria andRecvCityGreaterThan(String value) {
            addCriterion("recv_city >", value, "recvCity");
            return (Criteria) this;
        }

        public Criteria andRecvCityGreaterThanOrEqualTo(String value) {
            addCriterion("recv_city >=", value, "recvCity");
            return (Criteria) this;
        }

        public Criteria andRecvCityLessThan(String value) {
            addCriterion("recv_city <", value, "recvCity");
            return (Criteria) this;
        }

        public Criteria andRecvCityLessThanOrEqualTo(String value) {
            addCriterion("recv_city <=", value, "recvCity");
            return (Criteria) this;
        }

        public Criteria andRecvCityLike(String value) {
            addCriterion("recv_city like", value, "recvCity");
            return (Criteria) this;
        }

        public Criteria andRecvCityNotLike(String value) {
            addCriterion("recv_city not like", value, "recvCity");
            return (Criteria) this;
        }

        public Criteria andRecvCityIn(List<String> values) {
            addCriterion("recv_city in", values, "recvCity");
            return (Criteria) this;
        }

        public Criteria andRecvCityNotIn(List<String> values) {
            addCriterion("recv_city not in", values, "recvCity");
            return (Criteria) this;
        }

        public Criteria andRecvCityBetween(String value1, String value2) {
            addCriterion("recv_city between", value1, value2, "recvCity");
            return (Criteria) this;
        }

        public Criteria andRecvCityNotBetween(String value1, String value2) {
            addCriterion("recv_city not between", value1, value2, "recvCity");
            return (Criteria) this;
        }

        public Criteria andRecvAreaIsNull() {
            addCriterion("recv_area is null");
            return (Criteria) this;
        }

        public Criteria andRecvAreaIsNotNull() {
            addCriterion("recv_area is not null");
            return (Criteria) this;
        }

        public Criteria andRecvAreaEqualTo(String value) {
            addCriterion("recv_area =", value, "recvArea");
            return (Criteria) this;
        }

        public Criteria andRecvAreaNotEqualTo(String value) {
            addCriterion("recv_area <>", value, "recvArea");
            return (Criteria) this;
        }

        public Criteria andRecvAreaGreaterThan(String value) {
            addCriterion("recv_area >", value, "recvArea");
            return (Criteria) this;
        }

        public Criteria andRecvAreaGreaterThanOrEqualTo(String value) {
            addCriterion("recv_area >=", value, "recvArea");
            return (Criteria) this;
        }

        public Criteria andRecvAreaLessThan(String value) {
            addCriterion("recv_area <", value, "recvArea");
            return (Criteria) this;
        }

        public Criteria andRecvAreaLessThanOrEqualTo(String value) {
            addCriterion("recv_area <=", value, "recvArea");
            return (Criteria) this;
        }

        public Criteria andRecvAreaLike(String value) {
            addCriterion("recv_area like", value, "recvArea");
            return (Criteria) this;
        }

        public Criteria andRecvAreaNotLike(String value) {
            addCriterion("recv_area not like", value, "recvArea");
            return (Criteria) this;
        }

        public Criteria andRecvAreaIn(List<String> values) {
            addCriterion("recv_area in", values, "recvArea");
            return (Criteria) this;
        }

        public Criteria andRecvAreaNotIn(List<String> values) {
            addCriterion("recv_area not in", values, "recvArea");
            return (Criteria) this;
        }

        public Criteria andRecvAreaBetween(String value1, String value2) {
            addCriterion("recv_area between", value1, value2, "recvArea");
            return (Criteria) this;
        }

        public Criteria andRecvAreaNotBetween(String value1, String value2) {
            addCriterion("recv_area not between", value1, value2, "recvArea");
            return (Criteria) this;
        }

        public Criteria andRecvAddressIsNull() {
            addCriterion("recv_address is null");
            return (Criteria) this;
        }

        public Criteria andRecvAddressIsNotNull() {
            addCriterion("recv_address is not null");
            return (Criteria) this;
        }

        public Criteria andRecvAddressEqualTo(String value) {
            addCriterion("recv_address =", value, "recvAddress");
            return (Criteria) this;
        }

        public Criteria andRecvAddressNotEqualTo(String value) {
            addCriterion("recv_address <>", value, "recvAddress");
            return (Criteria) this;
        }

        public Criteria andRecvAddressGreaterThan(String value) {
            addCriterion("recv_address >", value, "recvAddress");
            return (Criteria) this;
        }

        public Criteria andRecvAddressGreaterThanOrEqualTo(String value) {
            addCriterion("recv_address >=", value, "recvAddress");
            return (Criteria) this;
        }

        public Criteria andRecvAddressLessThan(String value) {
            addCriterion("recv_address <", value, "recvAddress");
            return (Criteria) this;
        }

        public Criteria andRecvAddressLessThanOrEqualTo(String value) {
            addCriterion("recv_address <=", value, "recvAddress");
            return (Criteria) this;
        }

        public Criteria andRecvAddressLike(String value) {
            addCriterion("recv_address like", value, "recvAddress");
            return (Criteria) this;
        }

        public Criteria andRecvAddressNotLike(String value) {
            addCriterion("recv_address not like", value, "recvAddress");
            return (Criteria) this;
        }

        public Criteria andRecvAddressIn(List<String> values) {
            addCriterion("recv_address in", values, "recvAddress");
            return (Criteria) this;
        }

        public Criteria andRecvAddressNotIn(List<String> values) {
            addCriterion("recv_address not in", values, "recvAddress");
            return (Criteria) this;
        }

        public Criteria andRecvAddressBetween(String value1, String value2) {
            addCriterion("recv_address between", value1, value2, "recvAddress");
            return (Criteria) this;
        }

        public Criteria andRecvAddressNotBetween(String value1, String value2) {
            addCriterion("recv_address not between", value1, value2, "recvAddress");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNull() {
            addCriterion("total_price is null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIsNotNull() {
            addCriterion("total_price is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPriceEqualTo(Long value) {
            addCriterion("total_price =", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotEqualTo(Long value) {
            addCriterion("total_price <>", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThan(Long value) {
            addCriterion("total_price >", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("total_price >=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThan(Long value) {
            addCriterion("total_price <", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceLessThanOrEqualTo(Long value) {
            addCriterion("total_price <=", value, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceIn(List<Long> values) {
            addCriterion("total_price in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotIn(List<Long> values) {
            addCriterion("total_price not in", values, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceBetween(Long value1, Long value2) {
            addCriterion("total_price between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andTotalPriceNotBetween(Long value1, Long value2) {
            addCriterion("total_price not between", value1, value2, "totalPrice");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andOrderTimeIsNull() {
            addCriterion("order_time is null");
            return (Criteria) this;
        }

        public Criteria andOrderTimeIsNotNull() {
            addCriterion("order_time is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTimeEqualTo(Date value) {
            addCriterion("order_time =", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeNotEqualTo(Date value) {
            addCriterion("order_time <>", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeGreaterThan(Date value) {
            addCriterion("order_time >", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("order_time >=", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeLessThan(Date value) {
            addCriterion("order_time <", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeLessThanOrEqualTo(Date value) {
            addCriterion("order_time <=", value, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeIn(List<Date> values) {
            addCriterion("order_time in", values, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeNotIn(List<Date> values) {
            addCriterion("order_time not in", values, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeBetween(Date value1, Date value2) {
            addCriterion("order_time between", value1, value2, "orderTime");
            return (Criteria) this;
        }

        public Criteria andOrderTimeNotBetween(Date value1, Date value2) {
            addCriterion("order_time not between", value1, value2, "orderTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNull() {
            addCriterion("pay_time is null");
            return (Criteria) this;
        }

        public Criteria andPayTimeIsNotNull() {
            addCriterion("pay_time is not null");
            return (Criteria) this;
        }

        public Criteria andPayTimeEqualTo(Date value) {
            addCriterion("pay_time =", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotEqualTo(Date value) {
            addCriterion("pay_time <>", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThan(Date value) {
            addCriterion("pay_time >", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("pay_time >=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThan(Date value) {
            addCriterion("pay_time <", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeLessThanOrEqualTo(Date value) {
            addCriterion("pay_time <=", value, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeIn(List<Date> values) {
            addCriterion("pay_time in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotIn(List<Date> values) {
            addCriterion("pay_time not in", values, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeBetween(Date value1, Date value2) {
            addCriterion("pay_time between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andPayTimeNotBetween(Date value1, Date value2) {
            addCriterion("pay_time not between", value1, value2, "payTime");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIsNull() {
            addCriterion("created_user is null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIsNotNull() {
            addCriterion("created_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedUserEqualTo(String value) {
            addCriterion("created_user =", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotEqualTo(String value) {
            addCriterion("created_user <>", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserGreaterThan(String value) {
            addCriterion("created_user >", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserGreaterThanOrEqualTo(String value) {
            addCriterion("created_user >=", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLessThan(String value) {
            addCriterion("created_user <", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLessThanOrEqualTo(String value) {
            addCriterion("created_user <=", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserLike(String value) {
            addCriterion("created_user like", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotLike(String value) {
            addCriterion("created_user not like", value, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserIn(List<String> values) {
            addCriterion("created_user in", values, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotIn(List<String> values) {
            addCriterion("created_user not in", values, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserBetween(String value1, String value2) {
            addCriterion("created_user between", value1, value2, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedUserNotBetween(String value1, String value2) {
            addCriterion("created_user not between", value1, value2, "createdUser");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIsNull() {
            addCriterion("modified_user is null");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIsNotNull() {
            addCriterion("modified_user is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedUserEqualTo(String value) {
            addCriterion("modified_user =", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserNotEqualTo(String value) {
            addCriterion("modified_user <>", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserGreaterThan(String value) {
            addCriterion("modified_user >", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserGreaterThanOrEqualTo(String value) {
            addCriterion("modified_user >=", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserLessThan(String value) {
            addCriterion("modified_user <", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserLessThanOrEqualTo(String value) {
            addCriterion("modified_user <=", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserLike(String value) {
            addCriterion("modified_user like", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserNotLike(String value) {
            addCriterion("modified_user not like", value, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserIn(List<String> values) {
            addCriterion("modified_user in", values, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserNotIn(List<String> values) {
            addCriterion("modified_user not in", values, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserBetween(String value1, String value2) {
            addCriterion("modified_user between", value1, value2, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedUserNotBetween(String value1, String value2) {
            addCriterion("modified_user not between", value1, value2, "modifiedUser");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNull() {
            addCriterion("modified_time is null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNotNull() {
            addCriterion("modified_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeEqualTo(Date value) {
            addCriterion("modified_time =", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotEqualTo(Date value) {
            addCriterion("modified_time <>", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThan(Date value) {
            addCriterion("modified_time >", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_time >=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThan(Date value) {
            addCriterion("modified_time <", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
            addCriterion("modified_time <=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIn(List<Date> values) {
            addCriterion("modified_time in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotIn(List<Date> values) {
            addCriterion("modified_time not in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeBetween(Date value1, Date value2) {
            addCriterion("modified_time between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
            addCriterion("modified_time not between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 20 23:44:47 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}