package com.pirvate.store.entity;

import lombok.ToString;

import java.util.Date;
@ToString
public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.oid
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.uid
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.recv_name
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private String recvName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.recv_phone
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private String recvPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.recv_province
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private String recvProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.recv_city
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private String recvCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.recv_area
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private String recvArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.recv_address
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private String recvAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.total_price
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Long totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.created_user
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private String createdUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.created_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.modified_user
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private String modifiedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.modified_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.oid
     *
     * @return the value of t_order.oid
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.oid
     *
     * @param oid the value for t_order.oid
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.uid
     *
     * @return the value of t_order.uid
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.uid
     *
     * @param uid the value for t_order.uid
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.recv_name
     *
     * @return the value of t_order.recv_name
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public String getRecvName() {
        return recvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.recv_name
     *
     * @param recvName the value for t_order.recv_name
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setRecvName(String recvName) {
        this.recvName = recvName == null ? null : recvName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.recv_phone
     *
     * @return the value of t_order.recv_phone
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public String getRecvPhone() {
        return recvPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.recv_phone
     *
     * @param recvPhone the value for t_order.recv_phone
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setRecvPhone(String recvPhone) {
        this.recvPhone = recvPhone == null ? null : recvPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.recv_province
     *
     * @return the value of t_order.recv_province
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public String getRecvProvince() {
        return recvProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.recv_province
     *
     * @param recvProvince the value for t_order.recv_province
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setRecvProvince(String recvProvince) {
        this.recvProvince = recvProvince == null ? null : recvProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.recv_city
     *
     * @return the value of t_order.recv_city
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public String getRecvCity() {
        return recvCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.recv_city
     *
     * @param recvCity the value for t_order.recv_city
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setRecvCity(String recvCity) {
        this.recvCity = recvCity == null ? null : recvCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.recv_area
     *
     * @return the value of t_order.recv_area
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public String getRecvArea() {
        return recvArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.recv_area
     *
     * @param recvArea the value for t_order.recv_area
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setRecvArea(String recvArea) {
        this.recvArea = recvArea == null ? null : recvArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.recv_address
     *
     * @return the value of t_order.recv_address
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public String getRecvAddress() {
        return recvAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.recv_address
     *
     * @param recvAddress the value for t_order.recv_address
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setRecvAddress(String recvAddress) {
        this.recvAddress = recvAddress == null ? null : recvAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.total_price
     *
     * @return the value of t_order.total_price
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Long getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.total_price
     *
     * @param totalPrice the value for t_order.total_price
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setTotalPrice(Long totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status
     *
     * @return the value of t_order.status
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.status
     *
     * @param status the value for t_order.status
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_time
     *
     * @return the value of t_order.order_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_time
     *
     * @param orderTime the value for t_order.order_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_time
     *
     * @return the value of t_order.pay_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_time
     *
     * @param payTime the value for t_order.pay_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.created_user
     *
     * @return the value of t_order.created_user
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public String getCreatedUser() {
        return createdUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.created_user
     *
     * @param createdUser the value for t_order.created_user
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setCreatedUser(String createdUser) {
        this.createdUser = createdUser == null ? null : createdUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.created_time
     *
     * @return the value of t_order.created_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.created_time
     *
     * @param createdTime the value for t_order.created_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.modified_user
     *
     * @return the value of t_order.modified_user
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public String getModifiedUser() {
        return modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.modified_user
     *
     * @param modifiedUser the value for t_order.modified_user
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setModifiedUser(String modifiedUser) {
        this.modifiedUser = modifiedUser == null ? null : modifiedUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.modified_time
     *
     * @return the value of t_order.modified_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.modified_time
     *
     * @param modifiedTime the value for t_order.modified_time
     *
     * @mbggenerated Wed Jul 20 23:44:47 CST 2022
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}